[platformio]
default_envs = weact_stm32h562rg

[env:weact_stm32h562rg]
platform = ststm32
board = genericSTM32H562RG
framework = stm32cube
build_unflags =
  -std=gnu++11
build_flags =
  -std=c++17
  -O2
  -fno-exceptions
  -fno-rtti
  -fno-threadsafe-statics
  -Wall
  -DTARGET_STM32H562
  -Isrc
monitor_speed = 115200
